let data_add = [
    {
        "hhi": null,
        "id": "25d12ddf-67c4-4d2c-a291-86cf7c7f48ab",
        "title": null,
        "education": null,
        "ethnicity": null,
        "employmentStatus": null,
        "occupation": null,
        "religion": null,
        "favoriteBrand": null,
        "country": null,
        "region": null,
        "city": null,
        "address": null,
        "zipCode": null,
        "children": null,
        "pets": null,
        "superstar": null,
        "luxuryQualified": null,
        "createdAt": 1612005829000,
        "updatedAt": 1612005829000,
        "deletedAt": null,
        "teamId": 1,
        "labels": [],
        "notes": [],
        "email": "luckygirlsanna+10@gmail.com",
        "firstName": "Mary Tyler",
        "lastName": "Moore",
        "phone": "0987384756",
        "birthday": null,
        "gender": 10,
        "maritalStatus": 20,
        "bio": "",
        "registeredAt": 1612005945000,
        "lastActivityAt": 1612006002000,
        "image": null,
        "accountParameters": {
            "hhi": null,
            "education": null,
            "ethnicity": null,
            "employmentStatus": null,
            "occupation": null,
            "religion": null,
            "favoriteBrand": null,
            "country": "New York City",
            "region": null,
            "city": null,
            "address": null,
            "zipCode": null,
            "children": null,
            "pets": null
        },
        "studies": {"inactive": 0, "active": 0, "completed": 0}
    }, {
        "hhi": null,
        "id": "2776f7fe-d24a-417f-80a3-743c57da4bfc",
        "title": null,
        "education": null,
        "ethnicity": null,
        "employmentStatus": null,
        "occupation": null,
        "religion": null,
        "favoriteBrand": null,
        "country": null,
        "region": null,
        "city": null,
        "address": null,
        "zipCode": null,
        "children": null,
        "pets": null,
        "superstar": null,
        "luxuryQualified": null,
        "createdAt": 1611928389000,
        "updatedAt": 1611928389000,
        "deletedAt": null,
        "teamId": 1,
        "labels": [],
        "notes": [],
        "email": "prospect0009@mailinator.com",
        "firstName": "rsderf",
        "lastName": "rfsde",
        "phone": "drtgf",
        "birthday": null,
        "gender": null,
        "maritalStatus": null,
        "bio": "",
        "registeredAt": 1611928425000,
        "lastActivityAt": 1611928467000,
        "image": null,
        "accountParameters": {
            "hhi": null,
            "education": null,
            "ethnicity": null,
            "employmentStatus": null,
            "occupation": null,
            "religion": null,
            "favoriteBrand": null,
            "country": null,
            "region": null,
            "city": null,
            "address": null,
            "zipCode": null,
            "children": null,
            "pets": null
        },
        "studies": {"inactive": 1, "active": 0, "completed": 0}
    }
]

let data_1 = {
    "prospects": [
        {
            "hhi": null,
            "id": "0debe121-b06f-495f-ac42-9f61a073b3c1",
            "title": null,
            "education": null,
            "ethnicity": null,
            "employmentStatus": null,
            "occupation": null,
            "religion": null,
            "favoriteBrand": null,
            "country": null,
            "region": null,
            "city": null,
            "address": null,
            "zipCode": null,
            "children": null,
            "pets": null,
            "superstar": null,
            "luxuryQualified": null,
            "createdAt": 1611927580000,
            "updatedAt": 1611927580000,
            "deletedAt": null,
            "teamId": 1,
            "labels": [],
            "notes": [],
            "email": "prospect0008@mailinator.com",
            "firstName": "\tGordon",
            "lastName": "\tEllington",
            "phone": "156135136161",
            "birthday": null,
            "gender": null,
            "maritalStatus": null,
            "bio": "",
            "registeredAt": 1611927643000,
            "lastActivityAt": 1611928292000,
            "image": null,
            "accountParameters": {
                "hhi": null,
                "education": null,
                "ethnicity": null,
                "employmentStatus": null,
                "occupation": null,
                "religion": null,
                "favoriteBrand": null,
                "country": null,
                "region": null,
                "city": null,
                "address": null,
                "zipCode": null,
                "children": null,
                "pets": null
            },
            "studies": {"inactive": 1, "active": 0, "completed": 0}
        }, {
            "hhi": null,
            "id": "10b76ee3-a228-4a1e-b5fb-6a968ee8d0a5",
            "title": null,
            "education": null,
            "ethnicity": null,
            "employmentStatus": null,
            "occupation": null,
            "religion": null,
            "favoriteBrand": null,
            "country": null,
            "region": null,
            "city": null,
            "address": null,
            "zipCode": null,
            "children": null,
            "pets": null,
            "superstar": null,
            "luxuryQualified": null,
            "createdAt": 1612006362000,
            "updatedAt": 1612006362000,
            "deletedAt": null,
            "teamId": 1,
            "labels": [],
            "notes": [],
            "email": "luckygirlsanna+13@gmail.com",
            "firstName": "Jennifer",
            "lastName": "Lopez",
            "phone": "2340987890",
            "birthday": null,
            "gender": null,
            "maritalStatus": null,
            "bio": "",
            "registeredAt": 1612006430000,
            "lastActivityAt": 1612006455000,
            "image": null,
            "accountParameters": {
                "hhi": null,
                "education": null,
                "ethnicity": null,
                "employmentStatus": null,
                "occupation": null,
                "religion": null,
                "favoriteBrand": null,
                "country": null,
                "region": null,
                "city": null,
                "address": null,
                "zipCode": null,
                "children": null,
                "pets": null
            },
            "studies": {"inactive": 0, "active": 1, "completed": 0}
        }, {
            "hhi": null,
            "id": "11e7d971-80fb-42c8-88e7-9f90ae065c74",
            "title": null,
            "education": null,
            "ethnicity": null,
            "employmentStatus": null,
            "occupation": null,
            "religion": null,
            "favoriteBrand": null,
            "country": null,
            "region": null,
            "city": null,
            "address": null,
            "zipCode": null,
            "children": null,
            "pets": null,
            "superstar": null,
            "luxuryQualified": null,
            "createdAt": 1611843797000,
            "updatedAt": 1611843797000,
            "deletedAt": null,
            "teamId": 1,
            "labels": [],
            "notes": [],
            "email": "testest@mail.com",
            "firstName": null,
            "lastName": null,
            "phone": null,
            "birthday": null,
            "gender": null,
            "maritalStatus": null,
            "bio": null,
            "image": null,
            "accountParameters": {
                "hhi": null,
                "education": null,
                "ethnicity": null,
                "employmentStatus": null,
                "occupation": null,
                "religion": null,
                "favoriteBrand": null,
                "country": null,
                "region": null,
                "city": null,
                "address": null,
                "zipCode": null,
                "children": null,
                "pets": null
            },
            "studies": {"inactive": 1, "active": 0, "completed": 0}
        }, {
            "hhi": null,
            "id": "151fdd00-8de6-411f-8f6d-b41141a49138",
            "title": null,
            "education": null,
            "ethnicity": null,
            "employmentStatus": null,
            "occupation": null,
            "religion": null,
            "favoriteBrand": null,
            "country": null,
            "region": null,
            "city": null,
            "address": null,
            "zipCode": null,
            "children": null,
            "pets": null,
            "superstar": null,
            "luxuryQualified": null,
            "createdAt": 1611743072000,
            "updatedAt": 1611743072000,
            "deletedAt": null,
            "teamId": 1,
            "labels": [],
            "notes": [],
            "email": "monohrom98@gmail.com",
            "firstName": "SERGEY",
            "lastName": "GREBENYUK",
            "phone": "89094294989",
            "birthday": null,
            "gender": null,
            "maritalStatus": null,
            "bio": "",
            "registeredAt": 1611743178000,
            "lastActivityAt": 1611743286000,
            "image": null,
            "accountParameters": {
                "hhi": null,
                "education": null,
                "ethnicity": null,
                "employmentStatus": null,
                "occupation": null,
                "religion": null,
                "favoriteBrand": null,
                "country": null,
                "region": null,
                "city": null,
                "address": null,
                "zipCode": null,
                "children": null,
                "pets": null
            },
            "studies": {"inactive": 0, "active": 1, "completed": 0}
        }, {
            "hhi": null,
            "id": "161dc2cf-5bd9-4e48-9b08-3dcd486694d6",
            "title": null,
            "education": null,
            "ethnicity": null,
            "employmentStatus": null,
            "occupation": null,
            "religion": null,
            "favoriteBrand": null,
            "country": null,
            "region": null,
            "city": null,
            "address": null,
            "zipCode": null,
            "children": null,
            "pets": null,
            "superstar": null,
            "luxuryQualified": null,
            "createdAt": 1611866568000,
            "updatedAt": 1611866568000,
            "deletedAt": null,
            "teamId": 1,
            "labels": [],
            "notes": [],
            "email": "luckygirlsanna+6@gmail.com",
            "firstName": "Melanie",
            "lastName": "Maris",
            "phone": "7365820384",
            "birthday": null,
            "gender": null,
            "maritalStatus": null,
            "bio": "",
            "registeredAt": 1611866602000,
            "lastActivityAt": 1611914488000,
            "image": null,
            "accountParameters": {
                "hhi": null,
                "education": null,
                "ethnicity": null,
                "employmentStatus": null,
                "occupation": null,
                "religion": null,
                "favoriteBrand": null,
                "country": null,
                "region": null,
                "city": null,
                "address": null,
                "zipCode": null,
                "children": null,
                "pets": null
            },
            "studies": {"inactive": 0, "active": 2, "completed": 0}
        }, {
            "hhi": null,
            "id": "18b44e0b-9cbe-4579-afb8-a55e5234ab6c",
            "title": null,
            "education": null,
            "ethnicity": null,
            "employmentStatus": null,
            "occupation": null,
            "religion": null,
            "favoriteBrand": null,
            "country": null,
            "region": null,
            "city": null,
            "address": null,
            "zipCode": null,
            "children": null,
            "pets": null,
            "superstar": null,
            "luxuryQualified": null,
            "createdAt": 1612006526000,
            "updatedAt": 1612006526000,
            "deletedAt": null,
            "teamId": 1,
            "labels": [],
            "notes": [],
            "email": "luckygirlsanna+14@gmail.com",
            "firstName": "Lady",
            "lastName": "Gaga",
            "phone": "2340987234",
            "birthday": null,
            "gender": null,
            "maritalStatus": null,
            "bio": "",
            "registeredAt": 1612006581000,
            "lastActivityAt": 1612006667000,
            "image": null,
            "accountParameters": {
                "hhi": null,
                "education": null,
                "ethnicity": null,
                "employmentStatus": null,
                "occupation": null,
                "religion": null,
                "favoriteBrand": null,
                "country": null,
                "region": null,
                "city": null,
                "address": null,
                "zipCode": null,
                "children": null,
                "pets": null
            },
            "studies": {"inactive": 0, "active": 1, "completed": 0}
        }, {
            "hhi": null,
            "id": "331223ed-d58d-4c06-bd24-516de9476933",
            "title": null,
            "education": null,
            "ethnicity": null,
            "employmentStatus": null,
            "occupation": null,
            "religion": null,
            "favoriteBrand": null,
            "country": null,
            "region": null,
            "city": null,
            "address": null,
            "zipCode": null,
            "children": null,
            "pets": null,
            "superstar": null,
            "luxuryQualified": null,
            "createdAt": 1611738398000,
            "updatedAt": 1611738398000,
            "deletedAt": null,
            "teamId": 1,
            "labels": [],
            "notes": [],
            "email": "prospect0003@mailinator.com",
            "firstName": "Roxie",
            "lastName": "Flatcher",
            "phone": "159681961496",
            "birthday": null,
            "gender": null,
            "maritalStatus": null,
            "bio": "",
            "registeredAt": 1611739184000,
            "lastActivityAt": 1611825828000,
            "image": null,
            "accountParameters": {
                "hhi": null,
                "education": null,
                "ethnicity": null,
                "employmentStatus": null,
                "occupation": null,
                "religion": null,
                "favoriteBrand": null,
                "country": null,
                "region": null,
                "city": null,
                "address": null,
                "zipCode": null,
                "children": null,
                "pets": null
            },
            "studies": {"inactive": 0, "active": 3, "completed": 0}
        }, {
            "hhi": null,
            "id": "3654aaad-b86d-42b9-a571-9549d3d36dd9",
            "title": null,
            "education": null,
            "ethnicity": null,
            "employmentStatus": null,
            "occupation": null,
            "religion": null,
            "favoriteBrand": null,
            "country": null,
            "region": null,
            "city": null,
            "address": null,
            "zipCode": null,
            "children": null,
            "pets": null,
            "superstar": null,
            "luxuryQualified": null,
            "createdAt": 1612007002000,
            "updatedAt": 1612007002000,
            "deletedAt": null,
            "teamId": 1,
            "labels": [],
            "notes": [],
            "email": "luckygirlsanna+15@gmail.com",
            "firstName": "Ariane ",
            "lastName": "Grande",
            "phone": "2340987234",
            "birthday": null,
            "gender": null,
            "maritalStatus": null,
            "bio": "",
            "registeredAt": 1612007039000,
            "lastActivityAt": 1612100445000,
            "image": null,
            "accountParameters": {
                "hhi": null,
                "education": null,
                "ethnicity": null,
                "employmentStatus": null,
                "occupation": null,
                "religion": null,
                "favoriteBrand": null,
                "country": null,
                "region": null,
                "city": null,
                "address": null,
                "zipCode": null,
                "children": null,
                "pets": null
            },
            "studies": {"inactive": 0, "active": 1, "completed": 0}
        }],
    "totalRecords": 28
}

function prepare (data_1, data_add) {
    let result = []

    result = data_1.prospects.concat(data_add)
    // debug, проверить почему мало данных
    if (result.length !== data_1.totalRecords) {
        try {
            throw new Error('error_01 ' + result.length + ' !== ' + data_1.totalRecords)
        }
        finally {
            console.log('close connection')
        }
    }

    // проверить что мы имеем пользователей столько же, сколько в data_1.totalRecords, если не так, то выкинуть ошибку

    return result
}

try {
    prepare(data_1, data_add)
} catch (e) {
    console.error('error: ', e)
}

console.log()

// result [{ id, studies, registeredAt }, ...]

/*
data_1 = {
    prospects: [{}],
    totalRecords: Number
}

data_add = [{}]
*/